### ISSUE TITLE
como eu instalar no Windows

### ISSUE THREAD

**Issue by kirito18** [resultsystems/school#8]
hola como estas, como lo puedo instalar en windows, para poder probarlo e intentado de la manera normal, pero el sistema no corre. 

Nota:  Soy nuevo en laravel y se ve sumamente interesante tu sistema, si me puedes ayudar con los pasos de instalacion estaria agradecido

**Comment by emtudo** [comment]
Os passo para instalação está no readme, só seguir.

**Comment by kirito18** [comment]
pero lo puedo instalar en xampp, de modo localhost
